### ISSUE TITLE
When using controlnet Depth, After the most recent update, it causes a grey artifact overlay

### ISSUE THREAD

**Issue by AZvioh** [LonicaMewinsky/gif2gif#10]
I've tested and its only when controlnet is enabled.

**Comment by LonicaMewinsky** [comment]
![image](https://user-images.githubusercontent.com/93007558/222607284-a5a9dcd2-e8ce-4753-982f-0431abf1f5c2.png)
Try un-checking that and let me know?

**Comment by AZvioh** [comment]
will do https://streamable.com/1xyd5q here's a video of the issue

**Comment by AZvioh** [comment]
I checked the and unchecked it and the issue still happens

**Comment by AZvioh** [comment]
I can confirm that this wasn't happening before the update

**Comment by AZvioh** [comment]
It's also a lot more obvious the more movement there is, It's like the frames are layered on top of eachother

**Comment by AZvioh** [comment]
It's also a lot more obvious the more movement there is, It's like the frames are layered on top of each other.

**Comment by AZvioh** [comment]
It's also a lot more obvious the more movement there is, It's like the frames are layered on top of each other.

**Comment by LonicaMewinsky** [comment]
Recently-added behavior merges batches into one picture. It looks like, for some reason, controlnet is continuing to return a second image and merging it.

I just pushed a change that adds a check for this condition. Mind updating and trying again?

**Comment by AZvioh** [comment]
lets try

**Comment by AZvioh** [comment]
still says that I'm up to date

**Comment by AZvioh** [comment]
![Screenshot_30](https://user-images.githubusercontent.com/36087600/222611062-b21dc579-6578-4f88-8c08-3c88517d1966.png)
![Screenshot_29](https://user-images.githubusercontent.com/36087600/222611064-7dc1a22f-c57e-4a59-92f0-94497836d798.png)

**Comment by AZvioh** [comment]
Just manuely updated. Not only did you fix the issue. You added a feature I didn't know I needed. In the initial preview, It stacked all the frames, (for tracking faces, its useful to inpaint the least amount of area as possible. If you could fix this and add it as a feature that would be so dope.

**Comment by LonicaMewinsky** [comment]
It is indeed something I added earlier today for easier inpainting. I suppose toggling it on/off would make more sense.

Thanks a bunch for your help squashing this bug. :)

**Comment by AZvioh** [comment]
Thanks for fixing this with me :)
