### ISSUE TITLE
Tooltips overridden by same hints.js file

### ISSUE THREAD

**Issue by Harvester62** [LonicaMewinsky/gif2gif#11]
Hello @LonicaMewinsky , as reported in the AUTOMATIC1111 SD Web UI repository (https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7534) and in Prompt Generator's repository (https://github.com/imrayya/stable-diffusion-webui-Prompt_Generator/issues/15), because the hints.js file inside the \javascript folder has the same name of the SDWUI tooltips file, it overrides the original one, preventing the visualization of many tooltips when hovering the mouse on a label. 

To avoid this problem, the file should be renamed and the code inside it corrected. I have already done this for the Prompt Generator extension and I would be willing to do the same for you, if you have nothing in contrary. I have already tested the changes I made and they work. Therefore, I would fork your repository, create a new branch for the fix and apply it for a PR. Let me know if you have any comments.

**Comment by LonicaMewinsky** [comment]
Thanks a bunch sir. Just tested and merged it in. :)
