### ISSUE TITLE
Multiple control nets create a different Image when Gif2Gif is on vs off 

### ISSUE THREAD

**Issue by eldragon0** [LonicaMewinsky/gif2gif#13]
Currently utilizing 3 controlnets and everything is working great, however when I generate an image with gif2gif off I get a completely different result when it's turned on. This appears to have happened in the last couple days, previously it did work fine.

**Comment by LonicaMewinsky** [comment]
As-written, gif2gif will apply the gif frame to all cnet models, regardless of what you select on those models. This has not changed on this script's end, but it's possible something has changed for the ControlNet script.

Can you expand a bit? An example would be great if you can spare the time.

**Comment by eldragon0** [comment]
I'm working atm but will attempt to replicate this evening for you.

**Comment by eldragon0** [comment]
I've narrowed down the process that causes this issue, it may be niche, but it's an important part of my workflow. 
Once I get everything set up, I narrow down  depth_leres to only cover the background of my subject, then I take the output of that annotator result and set that as the input, then disable the preprocessor. While this seems silly it allows the background to be significantly more stable through the gif as long as the subject doesn't leave the mask this generates. It looks like the gif2gif throws out that mask and generates a new mask with each frame as though the preprocessor was turned on.

**Comment by LonicaMewinsky** [comment]
Thank sir. I've made a significant change to how the script handles ControlNet models. The old behavior would muscle the animation frames into every model. The new behavior will only replace input images where none are found. Care to update and give it a try?

**Comment by eldragon0** [comment]
Testing now

**Comment by eldragon0** [comment]
Works like a charm! One thing to note that should likely go on the description. If you put the gif into the control net model 
![image](https://user-images.githubusercontent.com/50936701/224189508-48cbb78d-1381-4089-9ebd-43c69af46a77.png)
Previously you'd be able to leave it there for and the script would as you stated before just brute force it's frames through. Now if you leave the gif there it will just take the first frame of the gif and use that over and over for each frame of the batch. This is a pretty non issue as you can tune the controlnet view the annotation output and drop the gif out of there. But worth noting that you do need to remove the gif from the controlnets you want the plugin to use populate with every frame.

**Comment by LonicaMewinsky** [comment]
Awesome. Definitely noted. And thanks for the kind words.

I'm probably going to stop development on gif2gif, FYI. Added gif support to [frame2frame](https://github.com/LonicaMewinsky/frame2frame), and eventually going to move all the functionality over there. I realized people are converting videos to gifs just to use this extension.. which is bonkers. haha
