### ISSUE TITLE
Outputs contain controlnet processed image

### ISSUE THREAD

**Issue by ampple** [LonicaMewinsky/gif2gif#24]
Outputs contain controlnet processed image overlayed over the main output.
![gif2gif-0000](https://user-images.githubusercontent.com/12243041/234970453-1586fa2d-4f34-4956-8009-8f7329b16a18.gif)

**Comment by LonicaMewinsky** [comment]
This behavior is consistent with "Do not append detectmap output.." option being unchecked in ControlNet:
![image](https://user-images.githubusercontent.com/93007558/234984972-e03e44a9-2f1a-410d-99f4-f620d3295685.png)

Mind checking that?

**Comment by ampple** [comment]
That solved it, thanks!

**Comment by Giganoob23** [comment]
@LonicaMewinsky Please add that somewhere in the instructions as I had the same issue and was about to open a new one.

**Comment by LonicaMewinsky** [comment]
> @LonicaMewinsky Please add that somewhere in the instructions as I had the same issue and was about to open a new one.

Sure thing. Also added a checkbox to disable the behavior entirely, just in case. :)
