### ISSUE TITLE
Inpainting error [ValueError: images do not match]

### ISSUE THREAD

**Issue by ShadowStorm0** [LonicaMewinsky/gif2gif#3]
I'm running commit "3715ece0adce7bf7c5e9c5ab3710b2fdc3848f39" of Automatic1111
When I try to inpaint and select "Only Masked", I get this error "ValueError: images do not match"

I followed this video "https://www.youtube.com/watch?v=F0oaHFVUSeY&start=479" and can not see anything different.

If anyone knows a solution to fix this, please reply to this issue.

**Comment by ShadowStorm0** [comment]
The issue has been resolved after I updated my extensions and restarted.
Not sure which extension bugged this feature.

**Comment by LonicaMewinsky** [comment]
Thanks for keeping me in the loop. Was about to investigate this further. :)

**Comment by ShadowStorm0** [comment]
@LonicaMewinsky Actually the Gif I have been trying to get working yesterday works now, but for some reason my other Gifs still get the same error. I don't understand why only one works. Please continue investigating

**Comment by ShadowStorm0** [comment]
I have a friend saying that the gif could have been cached and this may be causing the issue or a setting is wrong

**Comment by LonicaMewinsky** [comment]
Mind sharing a working and non-working gif? I can't seem to replicate this.
