### ISSUE TITLE
first frame is still wrong

### ISSUE THREAD

**Issue by Puddz** [LonicaMewinsky/gif2gif#4]
I've made sure to update to the latest version of it, but my first frame is still always completely different to the rest of the gif. At least when using controlnets.

**Comment by LonicaMewinsky** [comment]
There is an option in ControlNet settings, "Allow other script to control this extension." Can you confirm that is checked?

**Comment by Puddz** [comment]
It is. I think it was because I was using multiple controlnets. When I had them all enabled and set to a model, the gif worked fine. When 2 or 1 of the controlnet models wasn't enabled, the first image was completely different.

**Comment by LonicaMewinsky** [comment]
Added a safeguard to account for multiple controlnet models. Care to update and try again?

**Comment by Puddz** [comment]
Yeah it seems to be fixed now. Thank you.
