### ISSUE TITLE
[Feature Request] Add InfoText to the final GIF

### ISSUE THREAD

**Issue by MegaScience** [LonicaMewinsky/gif2gif#5]
The InfoText isn't applied to the final GIF, so if you're automatically clearing produced frames, you might not be able to reattempt a generation if you lose the generation parameters in the UI - especially if the seed is set to random. Is it possible to add the InfoText to the GIF with the utilized libraries, or would there need to be an extra step to apply it?

**Comment by LonicaMewinsky** [comment]
I'm not sure GIF format supports embedding metadata in the same way, but I can sure try. In the meantime, the generated text file (if using the option in WebUI settings) has all the information you're looking for.
![image](https://user-images.githubusercontent.com/93007558/221034856-c825bdbc-09f2-4083-a69f-eeb976b2febe.png)
![image](https://user-images.githubusercontent.com/93007558/221034968-777f987d-3f82-420e-ad3a-4805c627c594.png)

I'll leave this open until I can rule in/out the capability to embed GIF metadata. Thanks sir.

**Comment by LonicaMewinsky** [comment]
Greatly appreciate the suggestion. GIF format indeed does not support EXIF, but I was able to leverage the comment attribute and some trickery to get it to function with webui. Care to update and give it a try?

[gifcomment.webm](https://user-images.githubusercontent.com/93007558/222787309-aed2ecbe-bb03-4552-9019-9f159c002771.webm)

**Comment by MegaScience** [comment]
Works pretty well. For some reason hires fix gets enabled when transferring the contents across, but I think I've seen other things have the same issue, so not something you have to touch on.
