### ISSUE TITLE
Error. There is no gif generated

### ISSUE THREAD

**Issue by Maranpani** [LonicaMewinsky/gif2gif#6]
When i click on generate, i obtain only one image from my original gif.

Actual FPS ERROR

Actual Total Duration 

Actual total frames error!

[screen](https://user-images.githubusercontent.com/125226630/221427730-97620203-c496-41e3-99ee-516f9b5f0f6c.jpg)

**Comment by bodgingbrom** [comment]
Do you have the gif that you were using? It's hard to replicate stuff like this without an example. Is it doing the same thing on every gif you try?

**Comment by Maranpani** [comment]
> Do you have the gif that you were using? It's hard to replicate stuff like this without an example. Is it doing the same thing on every gif you try?

I find the way: we have to upload the gif again. I only putted on usual place. It's work but realistic gif seem complicated to do.

**Comment by LonicaMewinsky** [comment]
Correct -- you need to use the "upload GIF" button. If you have the GIF loaded and it still has problems when generated, let me know and I'll fix it up.
