### ISSUE TITLE
[Feature Request] Only use one controlnet for the input but multiple for the output?

### ISSUE THREAD

**Issue by Puddz** [LonicaMewinsky/gif2gif#8]
I don't know if its possible already but it doesn't seem like it is. 
Basically I would like the ability to tell the input gif to only go towards one of the controlnet models, and have the other controlnet models have a picture already that doesn't get changed by the input gif.

I don't know if im explaining this well or not.

**Comment by LonicaMewinsky** [comment]
You explained it fine. Maybe I can add a drop-down for "excluded controlnet models." You intend, for example, to leave a depth model static while a hed animates?

**Comment by Puddz** [comment]
Something like that yeah. 
Like a dancing video. 
Have the openpose animation animate and have a canny static background.

**Comment by LonicaMewinsky** [comment]
@Puddz, I've made a significant change to how the script handles ControlNet models. Rather than a "dropdown of avoided models," I opted to instead change the default behavior -- now, gif2gif will populate a model with an animation frame **only** if the model's image prompt is blank. So if you want an animation to drive the cnet model, leave the image blank. Otherwise, populate it with something like your canny background.

Care to update and give it a try?

**Comment by Puddz** [comment]
Bit confused about what you mean. 
I drop a gif into the gif2gif script, I then clear the image, and it gives me an error. "AttributeError: 'NoneType' object has no attribute 'convert'"
and I doubt you mean leaving the text fields blank because that would defeat the point of a prompting lol.

**Comment by LonicaMewinsky** [comment]
![image](https://user-images.githubusercontent.com/93007558/224188991-94732ec0-d386-40a6-be68-1dfaab7bb2c0.png)
By "prompt" I mean in an interface sense, not the text field. This is the window I'm talking about that should be left blank.

If you clear img2img you will indeed get an error.

**Comment by Puddz** [comment]
Ah. That works. Just needs some tweaking. And probably some way to tell the AI to keep the same character and clothes.... lol

https://imgur.com/rGh2fKT

But yeah, thanks for this.

**Comment by LonicaMewinsky** [comment]
No problem! Thanks for bringing this up.
