### ISSUE TITLE
PLEASE ADD SUPPORT FOR ONLY MASKED IMAGE PAINTING

### ISSUE THREAD

**Issue by AZvioh** [LonicaMewinsky/gif2gif#9]
This would be so useful. Right now it gives the error , images do not match.

**Comment by LonicaMewinsky** [comment]
Believe I've found the problem. This applies to images <480 pixel height. Larger images will work currently, and I'll have a fix shortly. Thanks sir.

**Comment by LonicaMewinsky** [comment]
Most recent push resolves this issue. :)
